quadruped_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - left_back_hip_joint
    - left_back_femur_joint
    - left_back_tibia_joint
    - left_front_hip_joint
    - left_front_femur_joint
    - left_front_tibia_joint
    - right_back_hip_joint
    - right_back_femur_joint
    - right_back_tibia_joint
    - right_front_hip_joint
    - right_front_femur_joint
    - right_front_tibia_joint
